// define all the error type here
exports.ERR_VERSION_NOT_ALLOWED = 'ERR_VERSION_NOT_ALLOWED';
exports.ERR_UNKNOWN = 'ERR_UNKNOWN';
exports.ERR_DUPLICATE_ENTRY = 'ERR_DUPLICATE_ENTRY';

// payment
exports.ERR_PAYMENT_NO_CARD = 'ERR_PAYMENT_NO_CARD';
exports.ERR_PAYMENT_CARD_DECLINED = 'ERR_PAYMENT_DECLINED';
exports.ERR_PAYMENT_FAILURE = 'ERR_PAYMENT_FAILURE';
exports.ERR_INVALID_DISCOUNT_CODE = 'ERR_INVALID_DISCOUNT_CODE';
